name: Random Activity Commits

on:
  schedule:
    # Runs on the 1st day of every month at midnight UTC
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update activity file
      run: |
        # Create or update activity.txt with current timestamp
        echo "Last activity: $(date)" > activity.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add activity.txt
        git commit -m "Automated monthly activity commit" || exit 0
        git push
